export const SET_NAME = "SET_NAME";
export const SET_LEFTPANEL_ISOPEN = "SET_LEFTPANEL_ISOPEN";
export const SET_SHAREMODAL_ISOPEN = "SET_SHAREMODAL_ISOPEN";
export const SET_WARNINGMODAL_ISOPEN = "SET_WARNINGMODAL_ISOPEN";
export const SET_WARNING_MODAL_ISOPEN = "SET_WARNING_MODAL_ISOPEN";
export const SET_CANCEL_SUBSCRIPTIONS_MODAL_ISOPEN = "SET_CANCEL_SUBSCRIPTIONS_MODAL_ISOPEN";
export const SET_SHAREMODAL_LINK = "SET_SHAREMODAL_LINK";
export const SET_SIGN_WAIVER_MODAL_ISOPEN = "SET_SIGN_WAIVER_MODAL_ISOPEN";
export const SET_USERROLE = "SET_USERROLE";

export const STORE_USER = '[user] STORE_USER';
