import Head from "next/head";
import Link from "next/link";
import DashboardLayout from "../../../src/components/layout/AdminDashboardLayout";
//Animation
import { motion } from "framer-motion";
//styles
import styled from "styled-components";

export default function AdminSuccessMessage() {
  return (
    <StyledDashboardLayout>
      <Head>
        <title>Success | HostShield</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledContent>
        <div className="flex flex-col shadow-2xl py-10 px-5 sm:px-10 w-11/12 sm:w-10/12 md:w-7/12 xl:w-5/12 2xl:w-4/12 space-y-9 justify-center mx-auto text-site-dark bg-white rounded-md">
          <div>
            <h3 className="text-4xl text-center font-semibold">
              Lawyer has been invited!
            </h3>
          </div>
          <Link href="/dashboard/admin">
            <a
              className="uppercase rounded-md  py-4 text-white bg-site-main text-sm font-medium text-center"
              type="button"
            >
              Back To Home Page
            </a>
          </Link>
        </div>
      </StyledContent>
    </StyledDashboardLayout>
  );
}

const StyledDashboardLayout = styled(DashboardLayout)``;
const StyledContent = styled(motion.section)`
  height: calc(100vh - 24vh);
  position: relative;
  & > div {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  }
`;
