import React, { Fragment, useState, useEffect } from "react";
//Components
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { useRouter } from "next/router";
import DashboardLayout from "../../../src/components/layout/AdminDashboardLayout";
import { Listbox, Transition } from "@headlessui/react";
import {
  StyledSignedSymbol,
  StyledOutForSignatureSymbol,
} from "../../../src/components/status";
//Icons
import { CheckIcon, ChevronDownIcon } from "@heroicons/react/solid";
import { FiSearch } from "react-icons/fi";
import { MdKeyboardArrowLeft } from "react-icons/md";
//Animation
import { motion } from "framer-motion";
//styles
import styled from "styled-components";
import { PUBLIC_API_KEY } from './../../../utils';

const approvedStatus = "approved";

const options = [
  { id: 1, name: "Newest" },
  { id: 2, name: "Oldest" },
];
const lawyer = {
    id: 1,
    current: true,
    email: "johndoe@email.com",
    username: "johndoe",
    fullname: "John Doe",
    image:
      "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60",
};

const MOCKED_PEOPLE = [
  {
    id: 1,
    status: "Approved",
    date: "22 Feb 2021",
    username: "johndoe",
    email: "jane.cooper@example.com",
    phoneNumber: "123 123 1234",
    image:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60",
  },
  {
    id: 2,
    status: "Waiting for approval",
    date: "23 Feb 2020",
    username: "johndoe",
    email: "jane.cooper@example.com",
    phoneNumber: "123 123 1234",
    image:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60",
  },
  {
    id: 3,
    status: "Approved",
    date: "23 May 2021",
    username: "johndoe",
    email: "jane.cooper@example.com",
    phoneNumber: "123 123 1234",
    image:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60",
  },
  {
    id: 4,
    status: "Waiting for approval",
    date: "15 Mar 2020",
    username: "joshdoe",
    email: "jane.cooper@example.com",
    phoneNumber: "123 123 1234",
    image:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60",
  },
  {
    id: 5,
    status: "Approved",
    date: "07 Jan 2021",
    username: "janedoe",
    email: "jane.cooper@example.com",
    phoneNumber: "123 123 1234",
    image:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60",
  },
];

const sortByDate = (arr, sortParam) => {
  return arr.sort((requestA, requestB) => {
    if (sortParam.name === 'Oldest') {
      return new Date(requestA.date).getTime() - new Date(requestB.date).getTime();
    }
    if (sortParam.name === 'Newest') {
      return new Date(requestB.date).getTime() - new Date(requestA.date).getTime();
    }
  })
}

export default function WaiverRequest() {
  const [selected, setSelected] = useState(options[0]);

  const [people, setPeople] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [email, setEmail] = useState('');
  const router = useRouter();

  const handleSearch = event => {
    setSearchTerm(event.target.value);
  }

  const handleSortParamChanged = (sortParam) => {
    const sortedArray = sortByDate([...people], sortParam);
    setSelected(sortParam);
    setPeople(sortedArray);
  }

  useEffect(() => {
    if (router.query.email) {
      setEmail(router.query.email);
    }
  }, [router]);

  useEffect(() => {
    if (router.query) {
      if (router.query.username) {

        // get lawyer requests
        const url = `${PUBLIC_API_KEY}/lawyer/requests?username=${router.query.username}`;
        fetch(url, {
          method: 'GET',
          credentials: 'include',
          headers: {
            'Content-Type': 'application/json'
          },
        }).then(response => {
          response.json().then(data => {
            const requests = [...data.approved, ...data.pending];
            // TODO: set people
            const sortedPeople = sortByDate(requests, {name: 'Newest'});
            setPeople(sortedPeople);  
          })
        }).catch(error => console.error(error));
      }
    }
  }, [router]);

  return (
    <DashboardLayout>
      <Head>
        <title>Lawyer | HostShield</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledMyWaiver className="flex flex-col px-3 md:ml-12 mt-10 mb-20 space-y-9 w-full md:w-11/12 text-site-dark">
        <div>
          <MdKeyboardArrowLeft className="text-xl inline-block" />
          <Link href="/dashboard/admin">
            <a className="text-sm font-medium text-site-dark">
              Back to Super Admin
            </a>
          </Link>
        </div>
        <LawyerUserContainer className="flex items-center w-full bg-white rounded-md px-3 py-3">
          {!!(email) && (
            <div key={email} className=" flex items-center space-x-4">
                <Image
                  className="rounded-full h-12 w-12"
                  src={lawyer.image}
                  alt={lawyer.fullname}
                  width="40"
                  height="40"
                />
                <span className="text-sm break-all text-site-darkergray">
                  {email}
                </span>
              </div>
          )}
        </LawyerUserContainer>
        <div className="flex justify-between">
          <h3 className="text-4xl font-semibold">Requests</h3>
        </div>
        <hr className="border-site-darkgray border-opacity-30" />
        <div className="flex flex-col space-y-3 md:space-y-0 md:flex-row md:justify-between">
          <div>
            <form className="w-full">
              <div className="flex w-full items-center relative">
                <input
                  type="text"
                  className="bg-input-gray w-full border-gray-100 focus:border-gray-300 focus:ring-0 font-light text-site-dark py-3 pl-5 pr-9 rounded-md placeholder-site-darkgray tracking-wide placeholder-opacity-70"
                  placeholder="Search..."
                  onChange={handleSearch}
                />
                <FiSearch className="absolute right-3 text-site-dark text-opacity-50 text-xl" />
              </div>
            </form>
          </div>
          <div className="w-full md:w-2/4 xl:w-1/4 flex sm:justify-end items-center space-x-2">
            <label className="sm:text-right w-1/4 xl:w-1/4 uppercase text-sm text-site-dark text-opacity-50">
              Sort By:
            </label>
            <Listbox className="w-3/4" value={selected} onChange={handleSortParamChanged}>
              {({ open }) => (
                <>
                  <div className="mt-1 w-3/4 sm:w-32 md:w-5/12 relative">
                    <Listbox.Button className="bg-transparent relative w-full border border-gray-200 rounded-md pl-3 pr-10 py-3 text-left cursor-default focus:outline-none focus:ring-0 tracking-wide text-sm">
                      <span className="block truncate">{selected.name}</span>
                      <span className="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
                        <ChevronDownIcon
                          className="h-5 w-5 text-gray-400"
                          aria-hidden="true"
                        />
                      </span>
                    </Listbox.Button>

                    <Transition
                      show={open}
                      as={Fragment}
                      leave="transition ease-in duration-100"
                      leaveFrom="opacity-100"
                      leaveTo="opacity-0"
                    >
                      <Listbox.Options
                        static
                        className="absolute z-10 mt-1 w-full bg-white shadow-lg max-h-60 rounded-md ring-1 ring-black ring-opacity-5 overflow-auto focus:outline-none text-sm"
                      >
                        {options.map((option) => (
                          <Listbox.Option
                            key={option.id}
                            className={({ active }) =>
                              classNames(
                                active
                                  ? "text-white bg-site-main"
                                  : "text-gray-900",
                                "cursor-default select-none relative py-2 pl-3 pr-9"
                              )
                            }
                            value={option}
                          >
                            {({ selected, active }) => (
                              <>
                                <span
                                  className={classNames(
                                    selected ? "font-semibold" : "font-normal",
                                    "block truncate"
                                  )}
                                >
                                  {option.name}
                                </span>

                                {selected ? (
                                  <span
                                    className={classNames(
                                      active ? "text-white" : "text-site-dark",
                                      "absolute inset-y-0 right-0 flex items-center pr-4"
                                    )}
                                  >
                                    <CheckIcon
                                      className="h-5 w-5"
                                      aria-hidden="true"
                                    />
                                  </span>
                                ) : null}
                              </>
                            )}
                          </Listbox.Option>
                        ))}
                      </Listbox.Options>
                    </Transition>
                  </div>
                </>
              )}
            </Listbox>
          </div>
        </div>
        <div className="flex flex-col space-y-4 overflow-x-scroll">
          <div className="flex w-max lg:w-full justify-start space-x-3 px-5">
            <div className="w-64 lg:w-4/12">
              <span className="text-sm uppercase text-site-dark tracking-wide font-medium">
                Email Address
              </span>
            </div>
            <div className="w-48 lg:w-3/12">
              <span className="text-sm uppercase text-site-dark tracking-wide font-medium">
                Status
              </span>
            </div>
            <div className="w-40 lg:w-2/12">
              <span className="text-sm uppercase text-site-dark tracking-wide font-medium">
                Username
              </span>
            </div>
            {/* <div className="w-40 lg:w-2/12">
              <span className="text-sm uppercase text-site-dark tracking-wide font-medium">
                Phone Number
              </span>
            </div> */}
            <div className="w-32 lg:w-2/12">
              <span className="text-sm uppercase text-site-dark tracking-wide font-medium">
                Date
              </span>
            </div>
            <div className="w-28 lg:w-2/12">
              <span className="sr-only">View Request</span>
            </div>
          </div>
          {people.filter(people => {
            if (searchTerm) {
              // search by username
              return people.username.startsWith(searchTerm);
            }
            return true;
          }).map((people) => (
            <StyledDataRow
              key={people.id}
              className="flex w-max lg:w-full justify-items-start space-x-3 rounded-md shadow-md bg-white px-5 py-4"
            >
              <div className="w-64 lg:w-4/12 overflow-x-hidden">
                <span className="text-sm break-words text-site-darkergray">
                  {people.email}
                </span>
              </div>
              <div className="w-48 lg:w-3/12">
                <span
                  className={`text-sm ${
                    people.status.toLowerCase() == approvedStatus.toLowerCase()
                      ? "text-site-green"
                      : "text-site-brown"
                  } tracking-wide`}
                >
                  {people.status.toLowerCase() ==
                  approvedStatus.toLowerCase() ? (
                    <StyledSignedSymbol />
                  ) : (
                    <StyledOutForSignatureSymbol />
                  )}
                  {people.status}
                </span>
              </div>
              <div className="w-40 lg:w-2/12">
                <span className="text-sm text-site-darkergray tracking-wide">
                  {people.username}
                </span>
              </div>
              {/* <div className="w-40 lg:w-2/12">
                <span className="text-sm text-site-darkergray tracking-wide">
                  {people.phoneNumber}
                </span>
              </div> */}
              <div className="w-32 lg:w-2/12">
                <span className="text-sm text-site-darkergray tracking-wide capitalize">
                  {people.date}
                </span>
              </div>
              <div className="w-28 lg:w-2/12">
                <Link href="#">
                  <a className="w-full inline-block text-sm font-medium text-right text-site-main tracking-wide capitalize">
                    View Request
                  </a>
                </Link>
              </div>
            </StyledDataRow>
          ))}
        </div>
      </StyledMyWaiver>
    </DashboardLayout>
  );
}

const StyledMyWaiver = styled(motion.section)`
  height: minmax(70vh, 90vh);
  @media (min-width: 1536px) {
    margin-bottom: 10rem;
  }
`;
const LawyerUserContainer = styled.div`
  box-shadow: 10px 0 90px 0 rgba(0, 0, 0, 0.05);
`;
const StyledDataRow = styled.div`
  box-shadow: 0 10px 90px 0 rgba(49, 49, 49, 0.05);
`;
function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}
