import React, { Fragment, useState, useEffect } from "react";
import { connect } from 'react-redux';
//Components
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import DashboardLayout from "../../../src/components/layout/AdminDashboardLayout";
import { Listbox, Transition } from "@headlessui/react";
import {
  StyledSignedSymbol,
  StyledOutForSignatureSymbol,
} from "../../../src/components/status";
//Icons
import { CheckIcon, ChevronDownIcon } from "@heroicons/react/solid";
import { FiSearch } from "react-icons/fi";
//Animation
import { motion } from "framer-motion";
//styles
import styled from "styled-components";
import { PUBLIC_API_KEY } from './../../../utils';

const APPROVED_STATUS = "approved";

const SORT_OPTIONS = [
  { id: 1, name: "Newest" },
  { id: 2, name: "Oldest" },
];

const sortByDate = (arr, sortParam) => {
  return arr.sort((requestA, requestB) => {
    if (sortParam.name === 'Oldest') {
      return new Date(requestA.date).getTime() - new Date(requestB.date).getTime();
    }
    if (sortParam.name === 'Newest') {
      return new Date(requestB.date).getTime() - new Date(requestA.date).getTime();
    }
  })
}

function WaiverRequest(props) {
  const router = useRouter();
  const [selected, setSelected] = useState(SORT_OPTIONS[0]);
  const [people, setPeople] = useState([]);
  const [searchTerm, setSearchTerm] = useState('');
  
  const {user} = props;

  const handleSearch = event => {
    setSearchTerm(event.target.value);
  }

  const handleSortParamChanged = (sortParam) => {
    const sortedArray = sortByDate([...people], sortParam);
    setSelected(sortParam);
    setPeople(sortedArray);
  }

  useEffect(() => {
    // check if user is logged in: if not, redirect to login page
    const userItem = JSON.parse(localStorage.getItem('user'));
      if (!userItem || !userItem.ttl || userItem.ttl < new Date().getTime()) {
        return router.push('/');
    }

    if (router?.query?.username) {
        // get requests
        const url = `${PUBLIC_API_KEY}/lawyer/requests?username=${router.query.username}`;
        fetch(url, {
          method: 'GET',
          credentials: 'include',
          headers: {
              'Content-Type': 'application/json'
          },
        }).then(response => {
        response.json().then(data => {
            // handle response
            const requests = [...data.approved, ...data.pending];
            // TODO: set people
            const sortedPeople = sortByDate(requests, {name: 'Newest'});
            setPeople(sortedPeople);
        });
        }).catch(error => console.error(error));
    }
  }, [router]);

  return (
    <DashboardLayout>
      <Head>
        <title>Request | HostShield</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledMyWaiver className="flex flex-col px-3 md:ml-12 mt-10 mb-20 space-y-9 w-full md:w-11/12 text-site-dark">
        <div className="flex justify-between">
          <h3 className="text-4xl font-semibold">Requests</h3>
        </div>
        <hr className="border-site-darkgray border-opacity-30" />
        <div className="flex flex-col space-y-3 sm:space-y-0 sm:flex-row w-full sm:justify-between">
          <div>
            <form className="w-full">
              <div className="flex w-full items-center relative">
                <input
                  type="text"
                  className="bg-input-gray w-full md:w-auto border-gray-100 focus:border-gray-300 focus:ring-0 font-light text-site-dark py-3 pl-5 pr-9 rounded-md placeholder-site-darkgray tracking-wide placeholder-opacity-70"
                  placeholder="Search..."
                  onChange={handleSearch}
                />
                <FiSearch className="absolute right-3 text-site-dark text-opacity-50 text-xl" />
              </div>
            </form>
          </div>
          <div className="w-full md:w-2/4 xl:w-1/4 flex sm:justify-end items-center space-x-2">
            <label className="sm:text-right w-1/4 xl:w-1/4 uppercase text-sm text-site-dark text-opacity-50">
              Sort By:
            </label>
            <Listbox className="w-3/4" value={selected} onChange={handleSortParamChanged}>
              {({ open }) => (
                <>
                  <div className="mt-1 w-3/4 sm:w-32 md:w-5/12 relative">
                    <Listbox.Button className="bg-transparent relative w-full border border-gray-200 rounded-md pl-3 pr-10 py-2 sm:py-3 text-left cursor-default focus:outline-none focus:ring-0 tracking-wide text-sm">
                      <span className="block truncate">{selected.name}</span>
                      <span className="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
                        <ChevronDownIcon
                          className="h-5 w-5 text-gray-400"
                          aria-hidden="true"
                        />
                      </span>
                    </Listbox.Button>

                    <Transition
                      show={open}
                      as={Fragment}
                      leave="transition ease-in duration-100"
                      leaveFrom="opacity-100"
                      leaveTo="opacity-0"
                    >
                      <Listbox.Options
                        static
                        className="absolute z-10 mt-1 w-full bg-white shadow-lg max-h-60 rounded-md text-base ring-1 ring-black ring-opacity-5 overflow-auto focus:outline-none sm:text-sm"
                      >
                        {SORT_OPTIONS.map((option) => (
                          <Listbox.Option
                            key={option.id}
                            className={({ active }) =>
                              classNames(
                                active
                                  ? "text-white bg-site-main"
                                  : "text-gray-900",
                                "cursor-default select-none relative py-2 pl-3 pr-9"
                              )
                            }
                            value={option}
                          >
                            {({ selected, active }) => (
                              <>
                                <span
                                  className={classNames(
                                    selected ? "font-semibold" : "font-normal",
                                    "block truncate"
                                  )}
                                >
                                  {option.name}
                                </span>

                                {selected ? (
                                  <span
                                    className={classNames(
                                      active ? "text-white" : "text-site-dark",
                                      "absolute inset-y-0 right-0 flex items-center pr-4"
                                    )}
                                  >
                                    <CheckIcon
                                      className="h-5 w-5"
                                      aria-hidden="true"
                                    />
                                  </span>
                                ) : null}
                              </>
                            )}
                          </Listbox.Option>
                        ))}
                      </Listbox.Options>
                    </Transition>
                  </div>
                </>
              )}
            </Listbox>
          </div>
        </div>
        <div className="flex flex-col space-y-4 overflow-x-scroll">
          <div className="flex w-max lg:w-full justify-start space-x-3 px-5">
            <div className="w-56 lg:w-4/12">
              <span className="text-sm uppercase text-site-dark tracking-wide font-medium">
                Email Address
              </span>
            </div>
            <div className="w-48 lg:w-3/12">
              <span className="text-sm uppercase text-site-dark tracking-wide font-medium">
                Status
              </span>
            </div>
            <div className="w-32 lg:w-2/12">
              <span className="text-sm uppercase text-site-dark tracking-wide font-medium">
                Username
              </span>
            </div>
            {/* <div className="w-32 lg:w-2/12 ">
              <span className="text-sm uppercase whitespace-nowrap text-site-dark tracking-wide font-medium">
                Phone Number
              </span>
            </div> */}
            <div className="w-32 lg:w-2/12">
              <span className="text-sm uppercase text-site-dark tracking-wide font-medium">
                Date
              </span>
            </div>
            <div className="w-32 lg:w-2/12">
              <span className="sr-only">View Request</span>
            </div>
          </div>
          {people.filter(people => {
            if (searchTerm) {
              // search by email
              return people?.email ? people.email.startsWith(searchTerm) : false;
            }
            return true;
          }).map((people) => (
            <StyledDataRow
              key={people.id}
              className="flex w-max lg:w-full justify-items-start space-x-3 rounded-md shadow-md bg-white px-5 py-4"
            >
              <div className="w-56 lg:w-4/12 overflow-x-hidden">
                <span className="text-sm break-words text-site-darkergray">
                  {people.email}
                </span>
              </div>
              <div className="w-48 lg:w-3/12">
                <span
                  className={`text-sm ${
                    people.status.toLowerCase() == APPROVED_STATUS.toLowerCase()
                      ? "text-site-green"
                      : "text-site-brown"
                  } tracking-wide`}
                >
                  {people.status.toLowerCase() ==
                  APPROVED_STATUS.toLowerCase() ? (
                    <StyledSignedSymbol />
                  ) : (
                    <StyledOutForSignatureSymbol />
                  )}
                  {people.status}
                </span>
              </div>
              <div className="w-32 lg:w-2/12">
                <span className="text-sm text-site-darkergray tracking-wide">
                  {people.username}
                </span>
              </div>
              {/* <div className="w-32 lg:w-2/12">
                <span className="text-sm text-site-darkergray tracking-wide">
                  {people.phoneNumber}
                </span>
              </div> */}
              <div className="w-32 lg:w-2/12">
                <span className="text-sm text-site-darkergray tracking-wide capitalize">
                  {people.date}
                </span>
              </div>
              <div className="w-32 lg:w-2/12">
                <Link href={`/dashboard/admin/waiver-approve-request?id=${people.id}&username=${router.query.username}`}>
                  <a className="w-full inline-block text-sm font-medium text-right text-site-main tracking-wide capitalize">
                    View Request
                  </a>
                </Link>
              </div>
            </StyledDataRow>
          ))}
        </div>
      </StyledMyWaiver>
    </DashboardLayout>
  );
}

const mapStateToProps = (state, props) => ({
  user: state.user.user,
});

export default connect(mapStateToProps, null)(WaiverRequest);

const StyledMyWaiver = styled(motion.section)`
  height: minmax(70vh, 90vh);
  @media (min-width: 1536px) {
    margin-bottom: 10rem;
  }
`;
const StyledDataRow = styled.div`
  box-shadow: 0 10px 90px 0 rgba(49, 49, 49, 0.05);
`;
function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}
