import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";
import { useState, useEffect } from "react";
//Logo
import Logo from "../src/components/header/logo";
//Backgrounds
import TransparentShieldBg from "../src/components/background/transparent-hostshield-bg";
//Animations
import { motion } from "framer-motion";
import { pageAnimation } from "../src/components/animation/index";
import Script from "next/script";

export default function RegistrationSuccess() {
  const [email,setEmail] = useState();
  useEffect(() => {
    const userItem = JSON.parse(localStorage.getItem("user"));
    setEmail(userItem.value.email);
  }, []);
  return (
    <div className="min-h-screen">
      <Head>
        <title>Registration Success | HostShield</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script strategy="afterInteractive">{`rewardful('convert', { email: '${email}' });`}</Script>
      <motion.section
        className=""
        exit="exit"
        variants={pageAnimation}
        initial="hidden"
        animate="show"
      >
        <div className="flex flex-col justify-between min-h-screen bg-section-gradient overflow-hidden text-white relative">
          <StyledLoginTransparentShieldBg className="inline-block w-screen h-screen absolute top-0 opacity-20" />
          <Logo className=" mt-5 w-56 h-32 mx-auto z-10" />
          <div className="flex justify-center flex-col px-1 lg:w-2/4 mx-auto z-10">
            <h3 className="text-center text-3xl lg:text-4xl">
              Successful Registration
            </h3>
            {/* Redirect to login screen */}
            <Link href="/">
              <a className="mt-10 w-3/4 2xl:w-2/4 py-4 bg-white mx-auto inline-block font-semibold text-site-main text-center uppercase text-base rounded-md tracking-wider cursor-pointer">
                Login
              </a>
            </Link>
          </div>
          <p className="text-center text-white mb-6 font-light text-opacity-50">
            {new Date().getFullYear()} &#169; HostShield
          </p>
        </div>
      </motion.section>
    </div>
  );
}

const StyledLoginTransparentShieldBg = styled(TransparentShieldBg)`
  right: -40%;
  @media (min-width: 1200px) {
    right: -50%;
  }
  @media (min-width: 1440px) {
    right: -50%;
  }
`;
